spring:
  profiles:
    active: prod

file:
  upload-dir: ./image

#  logback:
#    rollingpolicy:
#      max-history: 30
#      max-file-size: 50MB
#    org.hibernate.SQL: trace
#  org.hibernate.type: trace